import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { 
  Clock, Bot, Award, CheckCircle2, ChevronRight, 
  Briefcase, Send, Users, Sparkles, AlertCircle 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";

export default function ClientInterviewsPage() {
  const navigate = useNavigate();
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchInterviews();
  }, []);

  const fetchInterviews = async () => {
    setLoading(true);
    try {
      const { data } = await supabase
        .from("interview_reports")
        .select("*, candidate:candidates(*), job:jobs(*)")
        .order("created_at", { ascending: false });

      if (data && data.length > 0) {
        setReports(data);
      } else {
        // Fallback demo reports for MVP preview
        setReports([
          {
            session_id: "demo-session-1",
            overall_score: 92,
            recommendation: "Strongly Recommend",
            summary: "Candidate demonstrated deep production debugging experience in Node and Postgres.",
            candidate: {
              full_name: "Sarah Mensah",
              email: "sarah.mensah@example.com"
            },
            job: {
              title: "Senior Full Stack Engineer"
            },
            created_at: new Date().toISOString()
          },
          {
            session_id: "demo-session-2",
            overall_score: 84,
            recommendation: "Recommend",
            summary: "Solid problem solving skills with good system design awareness.",
            candidate: {
              full_name: "Alex Rivera",
              email: "alex.rivera@example.com"
            },
            job: {
              title: "AI Infrastructure Engineer"
            },
            created_at: new Date(Date.now() - 86400000).toISOString()
          }
        ]);
      }
    } catch (err) {
      console.error("Error fetching interviews:", err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 font-jakarta max-w-6xl mx-auto pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 text-emerald-600 text-xs font-bold uppercase tracking-widest mb-2">
            <Bot className="w-3.5 h-3.5" /> Automated Candidate Assessment Reports
          </div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight">AI Interviews & Evaluations</h1>
          <p className="text-sm font-medium text-slate-500 mt-1">
            Review evidence-based interview scoring and recommendations generated by Flowboard AI.
          </p>
        </div>

        <Button
          onClick={() => navigate("/client/roles")}
          className="h-11 px-6 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl shadow-lg shadow-emerald-600/20"
        >
          View Active Roles
        </Button>
      </div>

      {/* Reports List */}
      {loading ? (
        <div className="text-center py-16 text-slate-500 font-medium">Loading interview reports...</div>
      ) : (
        <div className="space-y-4">
          {reports.map((report) => (
            <div
              key={report.session_id}
              onClick={() => navigate(`/client/interviews/${report.session_id}`)}
              className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-all cursor-pointer flex flex-col md:flex-row md:items-center justify-between gap-6"
            >
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-2xl bg-emerald-50 text-emerald-600 font-black text-lg flex items-center justify-center shrink-0">
                  {report.overall_score}
                </div>

                <div>
                  <div className="flex items-center gap-3">
                    <h3 className="text-lg font-black text-slate-900 tracking-tight">
                      {report.candidate?.full_name || "Sarah Mensah"}
                    </h3>
                    <span className="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase bg-emerald-100 text-emerald-800">
                      {report.recommendation}
                    </span>
                  </div>

                  <p className="text-xs text-slate-500 font-semibold mt-0.5">
                    Role: <strong>{report.job?.title || "Senior Software Engineer"}</strong>
                  </p>

                  <p className="text-xs text-slate-600 font-medium line-clamp-1 mt-2">
                    {report.summary}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-4 border-t md:border-t-0 pt-4 md:pt-0 border-slate-100 justify-between md:justify-end">
                <span className="text-xs text-slate-400 font-medium flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" /> Completed {new Date(report.created_at).toLocaleDateString()}
                </span>

                <Button
                  size="sm"
                  className="h-10 px-5 text-xs font-bold rounded-xl bg-slate-900 hover:bg-slate-800 text-white"
                >
                  View Full Report <ChevronRight className="w-4 h-4 ml-1" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
